require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/directories", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Directory. As you add validations to Directory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Directory.create! valid_attributes
      get directories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      directory = Directory.create! valid_attributes
      get directory_url(directory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_directory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      directory = Directory.create! valid_attributes
      get edit_directory_url(directory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Directory" do
        expect {
          post directories_url, params: { directory: valid_attributes }
        }.to change(Directory, :count).by(1)
      end

      it "redirects to the created directory" do
        post directories_url, params: { directory: valid_attributes }
        expect(response).to redirect_to(directory_url(Directory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Directory" do
        expect {
          post directories_url, params: { directory: invalid_attributes }
        }.to change(Directory, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post directories_url, params: { directory: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested directory" do
        directory = Directory.create! valid_attributes
        patch directory_url(directory), params: { directory: new_attributes }
        directory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the directory" do
        directory = Directory.create! valid_attributes
        patch directory_url(directory), params: { directory: new_attributes }
        directory.reload
        expect(response).to redirect_to(directory_url(directory))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        directory = Directory.create! valid_attributes
        patch directory_url(directory), params: { directory: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested directory" do
      directory = Directory.create! valid_attributes
      expect {
        delete directory_url(directory)
      }.to change(Directory, :count).by(-1)
    end

    it "redirects to the directories list" do
      directory = Directory.create! valid_attributes
      delete directory_url(directory)
      expect(response).to redirect_to(directories_url)
    end
  end
end
